In [25]:
import pandas as pd

df = pd.read_csv("../data/raw/chicago_crimes.csv", nrows=100000)

df = df[
    [
        "Date",
        "Primary Type",
        "Latitude",
        "Longitude"
    ]
]

df = df.dropna(subset=["Latitude", "Longitude"])

df["Date"] = pd.to_datetime(df["Date"])

df["year"] = df["Date"].dt.year
df["month"] = df["Date"].dt.month

print(df.shape)

df.head()

(90895, 6)

                 Date     Primary Type   Latitude  Longitude  year  month
2 2020-08-10 09:45:00          ROBBERY  41.908418 -87.677407  2020      8
4 2023-09-06 17:00:00  CRIMINAL DAMAGE  41.886018 -87.633938  2023      9
5 2023-09-06 11:00:00            THEFT  41.871835 -87.626151  2023      9
6 2019-05-21 08:20:00         BURGLARY  41.856547 -87.695605  2019      5
7 2021-07-07 10:30:00      SEX OFFENSE  41.655116 -87.594883  2021      7

In [26]:
grid_size = 0.01

df["lat_bin"] = (df["Latitude"] / grid_size).round() * grid_size
df["lon_bin"] = (df["Longitude"] / grid_size).round() * grid_size

df.head()

,Date,Primary Type,Latitude,Longitude,year,month,lat_bin,lon_bin
2,2020-08-10 09:45:00,ROBBERY,41.908418,-87.677407,2020,8,41.91,-87.68
4,2023-09-06 17:00:00,CRIMINAL DAMAGE,41.886018,-87.633938,2023,9,41.89,-87.63
5,2023-09-06 11:00:00,THEFT,41.871835,-87.626151,2023,9,41.87,-87.63
6,2019-05-21 08:20:00,BURGLARY,41.856547,-87.695605,2019,5,41.86,-87.70
7,2021-07-07 10:30:00,SEX OFFENSE,41.655116,-87.594883,2021,7,41.66,-87.59

In [27]:
crime_grid = (
    df.groupby(
        ["lat_bin", "lon_bin", "year", "month"]
    )
    .size()
    .reset_index(name="crime_count")
)

crime_grid.head()

   lat_bin  lon_bin  year  month  crime_count
0    36.62   -91.69  2001      1            1
1    36.62   -91.69  2001      3            1
2    36.62   -91.69  2001      5            1
3    36.62   -91.69  2001      7            1
4    36.62   -91.69  2001      8            1

In [28]:
threshold = crime_grid["crime_count"].quantile(0.75)

crime_grid["hotspot"] = (
    crime_grid["crime_count"] >= threshold
).astype(int)

crime_grid.head()

   lat_bin  lon_bin  year  month  crime_count  hotspot
0    36.62   -91.69  2001      1            1        0
1    36.62   -91.69  2001      3            1        0
2    36.62   -91.69  2001      5            1        0
3    36.62   -91.69  2001      7            1        0
4    36.62   -91.69  2001      8            1        0

In [29]:
crime_grid["hotspot"].value_counts()

hotspot
0    9486
1    3351
Name: count, dtype: int64

In [30]:
features = [
    "lat_bin",
    "lon_bin",
    "year",
    "month"
]

X = crime_grid[features]
y = crime_grid["hotspot"]

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [32]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.05,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [33]:
from sklearn.metrics import classification_report

preds = model.predict(X_test)

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1898
           1       0.85      0.79      0.82       670

    accuracy                           0.91      2568
   macro avg       0.89      0.87      0.88      2568
weighted avg       0.91      0.91      0.91      2568

In [34]:
crime_grid["hotspot"].value_counts()

hotspot
0    9486
1    3351
Name: count, dtype: int64

In [35]:
crime_grid["risk_score"] = model.predict_proba(X)[:, 1]

In [36]:
import folium

In [37]:
m = folium.Map(
    location=[41.8781, -87.6298],
    zoom_start=11
)

In [38]:
sample_data = crime_grid.sample(1000)

for _, row in sample_data.iterrows():

    if row["risk_score"] > 0.7:
        color = "red"
    elif row["risk_score"] > 0.4:
        color = "orange"
    else:
        color = "green"

    folium.CircleMarker(
        location=[row["lat_bin"], row["lon_bin"]],
        radius=4,
        color=color,
        fill=True,
        fill_opacity=0.6,
        popup=f"Risk Score: {row['risk_score']:.2f}"
    ).add_to(m)

In [40]:
m

In [41]:
m.save("../outputs/hotspot_map.html")